# Generated by Django 4.1.1 on 2023-01-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_initial'),
        ('authentication', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.course'),
        ),
    ]
