# Generated by Django 4.1.1 on 2023-01-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_session_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(null=True, upload_to='exam'),
        ),
    ]
