# Generated by Django 4.1.1 on 2023-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0007_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exam',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
